### ISSUE TITLE
Has this method been tested on Kinetics?

### ISSUE THREAD

**Issue by bolin-chen** [kiyoon/PyVideoAI#1]
Hi! Thanks to your great work. Have you tested Time-Color Reordering and Grayscale Short-Term Stacking on Kinetics? I wonder if this method works on Kinetics.

**Comment by kiyoon** [comment]
Hi, I remember testing GrayST on a small subset of Kinetics with TSN. I saw 0.33% top-5 accuracy improvement but because Kinetics has a lot of environment bias it didn't show dramatic change (also didn't hurt the performance either).

**Comment by bolin-chen** [comment]
Get it. Thank you!
